/*!
 * Dynamic Time-shifting Desktop renderer main page
 * 
 * @author    Samuel Carreira <samuelcarreira@outlook.com>
 * @copyright (C) 2018 Samuel Carreira
 * @license   MIT
 * @version   See package.json
 */"use strict";const{ipcRenderer}=require("electron"),path=require("path");let wallpaperList=[];const el=document.getElementById("filelist-list");var sortable=new Sortable(el,{animation:250,onUpdate:function(){wallpaperList=reorderList()}});function reorderList(){const a=document.querySelectorAll("#filelist-list li");let b=[];return a.forEach(a=>{b.push(a.getAttribute("data-file"))}),ipcRenderer.send("ipcNewWallpaperList",b),b}ipcRenderer.on("ipcShowNotification",(a,b)=>{showNotification(b)}),ipcRenderer.on("ipcAddImages",(a,b)=>{wallpaperList.push(b),renderImageList(b)});function renderImageList(a){const b=document.getElementById("filelist-list");a.forEach(a=>{const c=path.basename(a),d=path.dirname(a),e=document.createElement("li");e.setAttribute("data-file",a),e.className="filelist-listitem",e.dataset.filename=a,e.innerHTML=`<div class="filelist-listitem-filenames">
        <p class="filelist-filename">${c}</p>
        <p class="filelist-path">${d}</p>
    </div>
    <div>
        <button title="Remove item from list" class="btn-remove-listitem">
            <img src="./assets/img/close-circle.svg" alt="X">
        </button>
    </div>`,b.appendChild(e)}),showHideTimeBar()}function showHideTimeBar(){const a=document.getElementById("filelist-list");100<a.clientHeight?(document.getElementById("filelist-time-container").style.visibility="visible",document.getElementById("filelist-time-container").style.height=a.clientHeight+"px"):document.getElementById("filelist-time-container").style.visibility="hidden"}function showNotification(a){if("object"!=typeof a||null===a)throw new Error("Must specify configuration object");"undefined"==typeof a.title&&a.title||(a.title="Dynamic Time-shifting Desktop"),"undefined"==typeof a.imagedata&&(a.imagedata=path.join(__dirname,"assets","icons","notification.png")),a.id||(a.id=String.fromCharCode(65+Math.floor(26*Math.random()))+Date.now());const b=[{title:a.title+"",body:(a.body+"").substring(0,250),icon:a.imagedata,tag:a.id,silent:!0}];try{const c=new Notification(b[0].title,b[0]);c.onclick=()=>{ipcRenderer.send("ipcNotificationClicked",a.id),void 0}}catch(a){}}document.onkeyup=function(a){a.preventDefault(),a=a||window.evt;var b=a.keyCode||a.which;116===b,112===b&&document.getElementById("dialog-tips").showModal()};function addEvent(a,b,c){a.addEventListener(b,c)}function live(a,b,c,d){addEvent(d||document,b,function(b){var e=(d||document).querySelectorAll(a);if(e){for(var f=b.target||b.srcElement,g=-1;f&&-1===(g=Array.prototype.indexOf.call(e,f));)f=f.parentElement;-1<g&&c.call(f,b)}})}live(".btn-remove-listitem","click",function(){const a=this;a.parentNode.parentNode.parentNode.removeChild(a.parentNode.parentNode),showHideTimeBar(),wallpaperList=reorderList()}),document.getElementById("btn-settings").onclick=()=>{ipcRenderer.send("ipcButtonSettings")},document.getElementById("btn-preview").onclick=()=>{ipcRenderer.send("ipcButtonPreview")},document.getElementById("btn-add-folder").onclick=()=>{ipcRenderer.send("ipcButtonAddFolder")},document.getElementById("btn-add-file").onclick=()=>{ipcRenderer.send("ipcButtonAddFile")},document.addEventListener("DOMContentLoaded",()=>{ipcRenderer.send("getInitialContent")});